"""Add user_agent to logs

Revision ID: 311da425e482
Revises: f6291d541cff
Create Date: 2025-11-09 12:42:44.900928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '311da425e482'
down_revision: Union[str, Sequence[str], None] = 'f6291d541cff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_logs', sa.Column('user_agent', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_logs', 'user_agent')
    # ### end Alembic commands ###
