"""Add user roles

Revision ID: ce9fbbf7af1e
Revises: 311da425e482
Create Date: 2025-11-09 16:14:59.452121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce9fbbf7af1e'
down_revision: Union[str, Sequence[str], None] = '311da425e482'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add column as nullable first
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    
    # 2. Update existing users to have 'employee' role
    op.execute("UPDATE users SET role = 'employee'")
    
    # 3. Now make it NOT NULL
    op.alter_column('users', 'role', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
